/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Yaxter API
 * Twitter-like demo API (ARCHITECTURE.md §1.2). This file is the source of
 * truth: Go server stubs, the Go client (seed/k6), and the SPA client
 * (orval, T1.7) are generated from it. All IDs are 64-bit snowflakes
 * serialized as decimal strings.
 *
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from './fetcher';
/**
 * Snowflake ID as a decimal string (int64-safe in JSON).
 * @pattern ^[0-9]+$
 */
export type Id = string;

export interface Error {
  /** Machine-readable code, e.g. validation_failed. */
  error: string;
  message: string;
}

export interface RegisterRequest {
  /** @pattern ^[A-Za-z0-9_]{3,30}$ */
  username: string;
  email: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
}

export interface LoginRequest {
  /** Username or email. */
  login: string;
  password: string;
}

export interface RefreshRequest {
  /** Omit when the HttpOnly refresh cookie is present (web). */
  refresh_token?: string;
}

export type TokenPairTokenType = typeof TokenPairTokenType[keyof typeof TokenPairTokenType];


export const TokenPairTokenType = {
  Bearer: 'Bearer',
} as const;

export interface TokenPair {
  access_token: string;
  token_type: TokenPairTokenType;
  /** Access-token lifetime in seconds (900 = 15 min). */
  expires_in: number;
  /** Returned in the body for non-web clients; web clients get a SameSite=Strict HttpOnly cookie instead. */
  refresh_token?: string;
}

export interface UserSummary {
  id: Id;
  username: string;
  /** @nullable */
  avatar_url?: string | null;
}

export interface User {
  id: Id;
  username: string;
  bio: string;
  /** @nullable */
  avatar_url?: string | null;
  followers_count: number;
  following_count: number;
  created_at: string;
}

export type PrivateUser = User & {
  email: string;
  /** false for OAuth-only accounts (pass_hash NULL). */
  has_password: boolean;
  linked_providers: string[];
};

export interface AuthResponse {
  user: PrivateUser;
  tokens: TokenPair;
}

export interface OAuthProviderInfo {
  name: string;
  display_name: string;
  start_url: string;
}

export interface ProviderList {
  providers: OAuthProviderInfo[];
}

export interface LinkStartResponse {
  /** Provider URL to complete linking in the browser. */
  auth_url: string;
}

export interface UpdateProfileRequest {
  /** @maxLength 160 */
  bio?: string;
  avatar_media_id?: Id;
}

/**
 * Fixed scheme https://media.{domain}/{variant}/{media_id}.webp (§2.5).
 */
export type MediaRefUrls = {
  thumb: string;
  feed: string;
  orig: string;
};

export interface MediaRef {
  id: Id;
  /** Fixed scheme https://media.{domain}/{variant}/{media_id}.webp (§2.5). */
  urls: MediaRefUrls;
}

export interface CreateTweetRequest {
  /**
     * May be empty only when retweet_of_id is set.
     * @maxLength 280
     */
  text: string;
  /**
     * Each must be in `ready` state.
     * @maxItems 4
     */
  media_ids?: Id[];
  retweet_of_id?: Id;
}

export interface Tweet {
  id: Id;
  author: UserSummary;
  text: string;
  /** One level deep — retweets of retweets are flattened to the original. */
  retweet_of?: Tweet | null;
  media?: MediaRef[];
  /** Eventual (±seconds), from the counter pipeline (§2.7). */
  likes_count: number;
  retweets_count: number;
  /** Present only on authenticated reads. */
  liked_by_me?: boolean;
  created_at: string;
}

export interface TweetPage {
  items: Tweet[];
  /**
     * Absent/null on the last page.
     * @nullable
     */
  next_cursor?: string | null;
}

export interface UserPage {
  items: UserSummary[];
  /** @nullable */
  next_cursor?: string | null;
}

export type NotificationKind = typeof NotificationKind[keyof typeof NotificationKind];


export const NotificationKind = {
  follow: 'follow',
  like: 'like',
  retweet: 'retweet',
  oauth_link: 'oauth_link',
} as const;

export interface Notification {
  id: Id;
  kind: NotificationKind;
  actor: UserSummary;
  /** Tweet ID for like/retweet; null for follow/oauth_link. */
  subject_id?: Id | null;
  created_at: string;
  read: boolean;
}

export interface NotificationPage {
  items: Notification[];
  /** @nullable */
  next_cursor?: string | null;
}

export interface UnreadCount {
  count: number;
}

export interface MarkReadRequest {
  up_to_id: Id;
}

export type CreateMediaRequestContentType = typeof CreateMediaRequestContentType[keyof typeof CreateMediaRequestContentType];


export const CreateMediaRequestContentType = {
  'image/jpeg': 'image/jpeg',
  'image/png': 'image/png',
  'image/webp': 'image/webp',
} as const;

export interface CreateMediaRequest {
  content_type: CreateMediaRequestContentType;
  /**
     * @minimum 1
     * @maximum 5242880
     */
  size_bytes: number;
}

export interface MediaUploadTicket {
  media_id: Id;
  /** Pre-signed PUT, scoped to exact key + content-length-range, 5-min expiry. */
  upload_url: string;
  expires_at: string;
}

export type MediaStatus = typeof MediaStatus[keyof typeof MediaStatus];


export const MediaStatus = {
  pending: 'pending',
  uploaded: 'uploaded',
  ready: 'ready',
  failed: 'failed',
} as const;

/**
 * Populated when status=ready.
 * @nullable
 */
export type MediaUrls = {
  thumb?: string;
  feed?: string;
  orig?: string;
} | null;

export interface Media {
  id: Id;
  status: MediaStatus;
  /**
     * Populated when status=ready.
     * @nullable
     */
  urls?: MediaUrls;
}

/**
 * Malformed request or validation failure.
 */
export type BadRequestResponse = Error;

/**
 * Missing/invalid/expired credentials.
 */
export type UnauthorizedResponse = Error;

/**
 * Authenticated but not allowed (ownership checks).
 */
export type ForbiddenResponse = Error;

/**
 * Resource does not exist (uniform — no enumeration leaks).
 */
export type NotFoundResponse = Error;

/**
 * State conflict (duplicate, in-flight idempotent request).
 */
export type ConflictResponse = Error;

/**
 * Rate limited.
 */
export type TooManyRequestsResponse = Error;

/**
 * UUID dedupe key; 24h window (ARCHITECTURE.md §7).
 */
export type IdempotencyKeyParameter = string;

/**
 * Opaque cursor from the previous page's next_cursor.
 */
export type CursorParameter = string;

export type LimitParameter = number;

export type OauthStartParams = {
/**
 * SPA route to return to after callback (validated allowlist).
 */
redirect_to?: string;
};

export type OauthCallbackParams = {
code: string;
state: string;
};

export type ListFollowersParams = {
/**
 * Opaque cursor from the previous page's next_cursor.
 */
cursor?: CursorParameter;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
};

export type ListFollowingParams = {
/**
 * Opaque cursor from the previous page's next_cursor.
 */
cursor?: CursorParameter;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
};

export type GetHomeTimelineParams = {
/**
 * Opaque cursor from the previous page's next_cursor.
 */
cursor?: CursorParameter;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
};

export type GetUserTweetsParams = {
/**
 * Opaque cursor from the previous page's next_cursor.
 */
cursor?: CursorParameter;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
};

export type ListNotificationsParams = {
/**
 * Opaque cursor from the previous page's next_cursor.
 */
cursor?: CursorParameter;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
};

export type registerResponse201 = {
  data: AuthResponse
  status: 201
}

export type registerResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type registerResponse409 = {
  data: ConflictResponse
  status: 409
}

export type registerResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

export type registerResponseSuccess = (registerResponse201) & {
  headers: Headers;
};
export type registerResponseError = (registerResponse400 | registerResponse409 | registerResponse429) & {
  headers: Headers;
};

export type registerResponse = (registerResponseSuccess | registerResponseError)

export const getRegisterUrl = () => {




  return `/v1/auth/register`
}

/**
 * @summary Create an account
 */
export const register = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerResponse> => {

  return customFetch<registerResponse>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest)
  }
);}



export type loginResponse200 = {
  data: AuthResponse
  status: 200
}

export type loginResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type loginResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401 | loginResponse429) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/v1/auth/login`
}

/**
 * @summary Log in with username/email + password
 */
export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {

  return customFetch<loginResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
);}



export type refreshTokenResponse200 = {
  data: TokenPair
  status: 200
}

export type refreshTokenResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type refreshTokenResponseSuccess = (refreshTokenResponse200) & {
  headers: Headers;
};
export type refreshTokenResponseError = (refreshTokenResponse401) & {
  headers: Headers;
};

export type refreshTokenResponse = (refreshTokenResponseSuccess | refreshTokenResponseError)

export const getRefreshTokenUrl = () => {




  return `/v1/auth/refresh`
}

/**
 * @summary Rotate the refresh token, issue a new pair
 */
export const refreshToken = async (refreshRequest?: RefreshRequest, options?: RequestInit): Promise<refreshTokenResponse> => {

  return customFetch<refreshTokenResponse>(getRefreshTokenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshRequest)
  }
);}



export type logoutResponse204 = {
  data: void
  status: 204
}

export type logoutResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type logoutResponseSuccess = (logoutResponse204) & {
  headers: Headers;
};
export type logoutResponseError = (logoutResponse401) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseSuccess | logoutResponseError)

export const getLogoutUrl = () => {




  return `/v1/auth/logout`
}

/**
 * @summary Revoke the current refresh-token family
 */
export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {

  return customFetch<logoutResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export type listAuthProvidersResponse200 = {
  data: ProviderList
  status: 200
}

export type listAuthProvidersResponseSuccess = (listAuthProvidersResponse200) & {
  headers: Headers;
};
;

export type listAuthProvidersResponse = (listAuthProvidersResponseSuccess)

export const getListAuthProvidersUrl = () => {




  return `/v1/auth/providers`
}

/**
 * @summary List enabled OAuth providers (config-driven)
 */
export const listAuthProviders = async ( options?: RequestInit): Promise<listAuthProvidersResponse> => {

  return customFetch<listAuthProvidersResponse>(getListAuthProvidersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type oauthStartResponse302 = {
  data: void
  status: 302
}

export type oauthStartResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type oauthStartResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

;
export type oauthStartResponseError = (oauthStartResponse302 | oauthStartResponse404 | oauthStartResponse429) & {
  headers: Headers;
};

export type oauthStartResponse = (oauthStartResponseError)

export const getOauthStartUrl = (provider: 'yandex' | 'google',
    params?: OauthStartParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/auth/oauth/${provider}/start?${stringifiedParams}` : `/v1/auth/oauth/${provider}/start`
}

/**
 * @summary Begin the authorization-code + PKCE dance
 */
export const oauthStart = async (provider: 'yandex' | 'google',
    params?: OauthStartParams, options?: RequestInit): Promise<oauthStartResponse> => {

  return customFetch<oauthStartResponse>(getOauthStartUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type oauthCallbackResponse200 = {
  data: AuthResponse
  status: 200
}

export type oauthCallbackResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type oauthCallbackResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type oauthCallbackResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

export type oauthCallbackResponseSuccess = (oauthCallbackResponse200) & {
  headers: Headers;
};
export type oauthCallbackResponseError = (oauthCallbackResponse400 | oauthCallbackResponse404 | oauthCallbackResponse429) & {
  headers: Headers;
};

export type oauthCallbackResponse = (oauthCallbackResponseSuccess | oauthCallbackResponseError)

export const getOauthCallbackUrl = (provider: 'yandex' | 'google',
    params: OauthCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/auth/oauth/${provider}/callback?${stringifiedParams}` : `/v1/auth/oauth/${provider}/callback`
}

/**
 * @summary Provider callback — exchange code, upsert identity, issue tokens
 */
export const oauthCallback = async (provider: 'yandex' | 'google',
    params: OauthCallbackParams, options?: RequestInit): Promise<oauthCallbackResponse> => {

  return customFetch<oauthCallbackResponse>(getOauthCallbackUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type oauthLinkResponse200 = {
  data: LinkStartResponse
  status: 200
}

export type oauthLinkResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type oauthLinkResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type oauthLinkResponse409 = {
  data: ConflictResponse
  status: 409
}

export type oauthLinkResponseSuccess = (oauthLinkResponse200) & {
  headers: Headers;
};
export type oauthLinkResponseError = (oauthLinkResponse401 | oauthLinkResponse404 | oauthLinkResponse409) & {
  headers: Headers;
};

export type oauthLinkResponse = (oauthLinkResponseSuccess | oauthLinkResponseError)

export const getOauthLinkUrl = (provider: 'yandex' | 'google',) => {




  return `/v1/auth/oauth/${provider}/link`
}

/**
 * @summary Start linking a provider to the authenticated account
 */
export const oauthLink = async (provider: 'yandex' | 'google', options?: RequestInit): Promise<oauthLinkResponse> => {

  return customFetch<oauthLinkResponse>(getOauthLinkUrl(provider),
  {
    ...options,
    method: 'POST'


  }
);}



export type oauthUnlinkResponse204 = {
  data: void
  status: 204
}

export type oauthUnlinkResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type oauthUnlinkResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type oauthUnlinkResponse409 = {
  data: Error
  status: 409
}

export type oauthUnlinkResponseSuccess = (oauthUnlinkResponse204) & {
  headers: Headers;
};
export type oauthUnlinkResponseError = (oauthUnlinkResponse401 | oauthUnlinkResponse404 | oauthUnlinkResponse409) & {
  headers: Headers;
};

export type oauthUnlinkResponse = (oauthUnlinkResponseSuccess | oauthUnlinkResponseError)

export const getOauthUnlinkUrl = (provider: 'yandex' | 'google',) => {




  return `/v1/auth/oauth/${provider}/link`
}

/**
 * @summary Unlink a provider
 */
export const oauthUnlink = async (provider: 'yandex' | 'google', options?: RequestInit): Promise<oauthUnlinkResponse> => {

  return customFetch<oauthUnlinkResponse>(getOauthUnlinkUrl(provider),
  {
    ...options,
    method: 'DELETE'


  }
);}



export type getMeResponse200 = {
  data: PrivateUser
  status: 200
}

export type getMeResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401) & {
  headers: Headers;
};

export type getMeResponse = (getMeResponseSuccess | getMeResponseError)

export const getGetMeUrl = () => {




  return `/v1/users/me`
}

/**
 * @summary Current user's profile (read-your-writes)
 */
export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {

  return customFetch<getMeResponse>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type updateMeResponse200 = {
  data: PrivateUser
  status: 200
}

export type updateMeResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateMeResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateMeResponseSuccess = (updateMeResponse200) & {
  headers: Headers;
};
export type updateMeResponseError = (updateMeResponse400 | updateMeResponse401) & {
  headers: Headers;
};

export type updateMeResponse = (updateMeResponseSuccess | updateMeResponseError)

export const getUpdateMeUrl = () => {




  return `/v1/users/me`
}

/**
 * @summary Update profile
 */
export const updateMe = async (updateProfileRequest: UpdateProfileRequest, options?: RequestInit): Promise<updateMeResponse> => {

  return customFetch<updateMeResponse>(getUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProfileRequest)
  }
);}



export type getUserResponse200 = {
  data: User
  status: 200
}

export type getUserResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
export type getUserResponseError = (getUserResponse404) & {
  headers: Headers;
};

export type getUserResponse = (getUserResponseSuccess | getUserResponseError)

export const getGetUserUrl = (username: string,) => {




  return `/v1/users/${username}`
}

/**
 * @summary Public profile
 */
export const getUser = async (username: string, options?: RequestInit): Promise<getUserResponse> => {

  return customFetch<getUserResponse>(getGetUserUrl(username),
  {
    ...options,
    method: 'GET'


  }
);}



export type followUserResponse204 = {
  data: void
  status: 204
}

export type followUserResponse400 = {
  data: Error
  status: 400
}

export type followUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type followUserResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type followUserResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

export type followUserResponseSuccess = (followUserResponse204) & {
  headers: Headers;
};
export type followUserResponseError = (followUserResponse400 | followUserResponse401 | followUserResponse404 | followUserResponse429) & {
  headers: Headers;
};

export type followUserResponse = (followUserResponseSuccess | followUserResponseError)

export const getFollowUserUrl = (username: string,) => {




  return `/v1/users/${username}/follow`
}

/**
 * @summary Follow a user (idempotent; writes both edge tables + event in one tx)
 */
export const followUser = async (username: string, options?: RequestInit): Promise<followUserResponse> => {

  return customFetch<followUserResponse>(getFollowUserUrl(username),
  {
    ...options,
    method: 'POST'


  }
);}



export type unfollowUserResponse204 = {
  data: void
  status: 204
}

export type unfollowUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type unfollowUserResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type unfollowUserResponseSuccess = (unfollowUserResponse204) & {
  headers: Headers;
};
export type unfollowUserResponseError = (unfollowUserResponse401 | unfollowUserResponse404) & {
  headers: Headers;
};

export type unfollowUserResponse = (unfollowUserResponseSuccess | unfollowUserResponseError)

export const getUnfollowUserUrl = (username: string,) => {




  return `/v1/users/${username}/follow`
}

/**
 * @summary Unfollow a user (idempotent)
 */
export const unfollowUser = async (username: string, options?: RequestInit): Promise<unfollowUserResponse> => {

  return customFetch<unfollowUserResponse>(getUnfollowUserUrl(username),
  {
    ...options,
    method: 'DELETE'


  }
);}



export type listFollowersResponse200 = {
  data: UserPage
  status: 200
}

export type listFollowersResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listFollowersResponseSuccess = (listFollowersResponse200) & {
  headers: Headers;
};
export type listFollowersResponseError = (listFollowersResponse404) & {
  headers: Headers;
};

export type listFollowersResponse = (listFollowersResponseSuccess | listFollowersResponseError)

export const getListFollowersUrl = (username: string,
    params?: ListFollowersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/users/${username}/followers?${stringifiedParams}` : `/v1/users/${username}/followers`
}

/**
 * @summary Who follows this user
 */
export const listFollowers = async (username: string,
    params?: ListFollowersParams, options?: RequestInit): Promise<listFollowersResponse> => {

  return customFetch<listFollowersResponse>(getListFollowersUrl(username,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type listFollowingResponse200 = {
  data: UserPage
  status: 200
}

export type listFollowingResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listFollowingResponseSuccess = (listFollowingResponse200) & {
  headers: Headers;
};
export type listFollowingResponseError = (listFollowingResponse404) & {
  headers: Headers;
};

export type listFollowingResponse = (listFollowingResponseSuccess | listFollowingResponseError)

export const getListFollowingUrl = (username: string,
    params?: ListFollowingParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/users/${username}/following?${stringifiedParams}` : `/v1/users/${username}/following`
}

/**
 * @summary Who this user follows
 */
export const listFollowing = async (username: string,
    params?: ListFollowingParams, options?: RequestInit): Promise<listFollowingResponse> => {

  return customFetch<listFollowingResponse>(getListFollowingUrl(username,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type createTweetResponse201 = {
  data: Tweet
  status: 201
}

export type createTweetResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createTweetResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createTweetResponse404 = {
  data: Error
  status: 404
}

export type createTweetResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

export type createTweetResponseSuccess = (createTweetResponse201) & {
  headers: Headers;
};
export type createTweetResponseError = (createTweetResponse400 | createTweetResponse401 | createTweetResponse404 | createTweetResponse429) & {
  headers: Headers;
};

export type createTweetResponse = (createTweetResponseSuccess | createTweetResponseError)

export const getCreateTweetUrl = () => {




  return `/v1/tweets`
}

/**
 * @summary Create a tweet or retweet (retweet_of_id set)
 */
export const createTweet = async (createTweetRequest: CreateTweetRequest, options?: RequestInit): Promise<createTweetResponse> => {

  return customFetch<createTweetResponse>(getCreateTweetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTweetRequest)
  }
);}



export type getTweetResponse200 = {
  data: Tweet
  status: 200
}

export type getTweetResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getTweetResponseSuccess = (getTweetResponse200) & {
  headers: Headers;
};
export type getTweetResponseError = (getTweetResponse404) & {
  headers: Headers;
};

export type getTweetResponse = (getTweetResponseSuccess | getTweetResponseError)

export const getGetTweetUrl = (id: string,) => {




  return `/v1/tweets/${id}`
}

/**
 * @summary Fetch one tweet
 */
export const getTweet = async (id: string, options?: RequestInit): Promise<getTweetResponse> => {

  return customFetch<getTweetResponse>(getGetTweetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type deleteTweetResponse204 = {
  data: void
  status: 204
}

export type deleteTweetResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteTweetResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteTweetResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteTweetResponseSuccess = (deleteTweetResponse204) & {
  headers: Headers;
};
export type deleteTweetResponseError = (deleteTweetResponse401 | deleteTweetResponse403 | deleteTweetResponse404) & {
  headers: Headers;
};

export type deleteTweetResponse = (deleteTweetResponseSuccess | deleteTweetResponseError)

export const getDeleteTweetUrl = (id: string,) => {




  return `/v1/tweets/${id}`
}

/**
 * @summary Delete own tweet
 */
export const deleteTweet = async (id: string, options?: RequestInit): Promise<deleteTweetResponse> => {

  return customFetch<deleteTweetResponse>(getDeleteTweetUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export type likeTweetResponse204 = {
  data: void
  status: 204
}

export type likeTweetResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type likeTweetResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type likeTweetResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

export type likeTweetResponseSuccess = (likeTweetResponse204) & {
  headers: Headers;
};
export type likeTweetResponseError = (likeTweetResponse401 | likeTweetResponse404 | likeTweetResponse429) & {
  headers: Headers;
};

export type likeTweetResponse = (likeTweetResponseSuccess | likeTweetResponseError)

export const getLikeTweetUrl = (id: string,) => {




  return `/v1/tweets/${id}/like`
}

/**
 * @summary Like (idempotent — PK ON CONFLICT DO NOTHING)
 */
export const likeTweet = async (id: string, options?: RequestInit): Promise<likeTweetResponse> => {

  return customFetch<likeTweetResponse>(getLikeTweetUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



export type unlikeTweetResponse204 = {
  data: void
  status: 204
}

export type unlikeTweetResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type unlikeTweetResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type unlikeTweetResponseSuccess = (unlikeTweetResponse204) & {
  headers: Headers;
};
export type unlikeTweetResponseError = (unlikeTweetResponse401 | unlikeTweetResponse404) & {
  headers: Headers;
};

export type unlikeTweetResponse = (unlikeTweetResponseSuccess | unlikeTweetResponseError)

export const getUnlikeTweetUrl = (id: string,) => {




  return `/v1/tweets/${id}/like`
}

/**
 * @summary Unlike (idempotent)
 */
export const unlikeTweet = async (id: string, options?: RequestInit): Promise<unlikeTweetResponse> => {

  return customFetch<unlikeTweetResponse>(getUnlikeTweetUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export type getHomeTimelineResponse200 = {
  data: TweetPage
  status: 200
}

export type getHomeTimelineResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getHomeTimelineResponseSuccess = (getHomeTimelineResponse200) & {
  headers: Headers;
};
export type getHomeTimelineResponseError = (getHomeTimelineResponse401) & {
  headers: Headers;
};

export type getHomeTimelineResponse = (getHomeTimelineResponseSuccess | getHomeTimelineResponseError)

export const getGetHomeTimelineUrl = (params?: GetHomeTimelineParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/timeline?${stringifiedParams}` : `/v1/timeline`
}

/**
 * @summary Home timeline (hybrid fan-out merge, §2.1; eventual <5s)
 */
export const getHomeTimeline = async (params?: GetHomeTimelineParams, options?: RequestInit): Promise<getHomeTimelineResponse> => {

  return customFetch<getHomeTimelineResponse>(getGetHomeTimelineUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type getUserTweetsResponse200 = {
  data: TweetPage
  status: 200
}

export type getUserTweetsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getUserTweetsResponseSuccess = (getUserTweetsResponse200) & {
  headers: Headers;
};
export type getUserTweetsResponseError = (getUserTweetsResponse404) & {
  headers: Headers;
};

export type getUserTweetsResponse = (getUserTweetsResponseSuccess | getUserTweetsResponseError)

export const getGetUserTweetsUrl = (username: string,
    params?: GetUserTweetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/users/${username}/tweets?${stringifiedParams}` : `/v1/users/${username}/tweets`
}

/**
 * @summary Profile timeline
 */
export const getUserTweets = async (username: string,
    params?: GetUserTweetsParams, options?: RequestInit): Promise<getUserTweetsResponse> => {

  return customFetch<getUserTweetsResponse>(getGetUserTweetsUrl(username,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type listNotificationsResponse200 = {
  data: NotificationPage
  status: 200
}

export type listNotificationsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listNotificationsResponseSuccess = (listNotificationsResponse200) & {
  headers: Headers;
};
export type listNotificationsResponseError = (listNotificationsResponse401) & {
  headers: Headers;
};

export type listNotificationsResponse = (listNotificationsResponseSuccess | listNotificationsResponseError)

export const getListNotificationsUrl = (params?: ListNotificationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/notifications?${stringifiedParams}` : `/v1/notifications`
}

/**
 * @summary List notifications (eventual, <30s)
 */
export const listNotifications = async (params?: ListNotificationsParams, options?: RequestInit): Promise<listNotificationsResponse> => {

  return customFetch<listNotificationsResponse>(getListNotificationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type getUnreadCountResponse200 = {
  data: UnreadCount
  status: 200
}

export type getUnreadCountResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getUnreadCountResponseSuccess = (getUnreadCountResponse200) & {
  headers: Headers;
};
export type getUnreadCountResponseError = (getUnreadCountResponse401) & {
  headers: Headers;
};

export type getUnreadCountResponse = (getUnreadCountResponseSuccess | getUnreadCountResponseError)

export const getGetUnreadCountUrl = () => {




  return `/v1/notifications/unread_count`
}

/**
 * @summary Unread badge counter
 */
export const getUnreadCount = async ( options?: RequestInit): Promise<getUnreadCountResponse> => {

  return customFetch<getUnreadCountResponse>(getGetUnreadCountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type markNotificationsReadResponse204 = {
  data: void
  status: 204
}

export type markNotificationsReadResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type markNotificationsReadResponseSuccess = (markNotificationsReadResponse204) & {
  headers: Headers;
};
export type markNotificationsReadResponseError = (markNotificationsReadResponse401) & {
  headers: Headers;
};

export type markNotificationsReadResponse = (markNotificationsReadResponseSuccess | markNotificationsReadResponseError)

export const getMarkNotificationsReadUrl = () => {




  return `/v1/notifications/read`
}

/**
 * @summary Mark all notifications up to an ID as read
 */
export const markNotificationsRead = async (markReadRequest: MarkReadRequest, options?: RequestInit): Promise<markNotificationsReadResponse> => {

  return customFetch<markNotificationsReadResponse>(getMarkNotificationsReadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(markReadRequest)
  }
);}



export type createMediaResponse201 = {
  data: MediaUploadTicket
  status: 201
}

export type createMediaResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createMediaResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createMediaResponse429 = {
  data: TooManyRequestsResponse
  status: 429
}

export type createMediaResponseSuccess = (createMediaResponse201) & {
  headers: Headers;
};
export type createMediaResponseError = (createMediaResponse400 | createMediaResponse401 | createMediaResponse429) & {
  headers: Headers;
};

export type createMediaResponse = (createMediaResponseSuccess | createMediaResponseError)

export const getCreateMediaUrl = () => {




  return `/v1/media`
}

/**
 * @summary Allocate media ID and pre-signed upload URL (§2.5)
 */
export const createMedia = async (createMediaRequest: CreateMediaRequest, options?: RequestInit): Promise<createMediaResponse> => {

  return customFetch<createMediaResponse>(getCreateMediaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createMediaRequest)
  }
);}



export type getMediaResponse200 = {
  data: Media
  status: 200
}

export type getMediaResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMediaResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMediaResponseSuccess = (getMediaResponse200) & {
  headers: Headers;
};
export type getMediaResponseError = (getMediaResponse401 | getMediaResponse404) & {
  headers: Headers;
};

export type getMediaResponse = (getMediaResponseSuccess | getMediaResponseError)

export const getGetMediaUrl = (id: string,) => {




  return `/v1/media/${id}`
}

/**
 * @summary Media processing status
 */
export const getMedia = async (id: string, options?: RequestInit): Promise<getMediaResponse> => {

  return customFetch<getMediaResponse>(getGetMediaUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type completeMediaResponse200 = {
  data: Media
  status: 200
}

export type completeMediaResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type completeMediaResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type completeMediaResponse409 = {
  data: Error
  status: 409
}

export type completeMediaResponseSuccess = (completeMediaResponse200) & {
  headers: Headers;
};
export type completeMediaResponseError = (completeMediaResponse401 | completeMediaResponse404 | completeMediaResponse409) & {
  headers: Headers;
};

export type completeMediaResponse = (completeMediaResponseSuccess | completeMediaResponseError)

export const getCompleteMediaUrl = (id: string,) => {




  return `/v1/media/${id}/complete`
}

/**
 * @summary Confirm upload — verifies object exists, emits MediaUploaded via outbox
 */
export const completeMedia = async (id: string, options?: RequestInit): Promise<completeMediaResponse> => {

  return customFetch<completeMediaResponse>(getCompleteMediaUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}
