apiVersion: v1
kind: Service
metadata:
  name: {{ include "yaxter.fullname" . }}-api
  labels:
    {{- include "yaxter.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "yaxter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
