//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CreateMediaRequestContentType.
const (
	Imagejpeg CreateMediaRequestContentType = "image/jpeg"
	Imagepng  CreateMediaRequestContentType = "image/png"
	Imagewebp CreateMediaRequestContentType = "image/webp"
)

// Defines values for MediaStatus.
const (
	Failed   MediaStatus = "failed"
	Pending  MediaStatus = "pending"
	Ready    MediaStatus = "ready"
	Uploaded MediaStatus = "uploaded"
)

// Defines values for NotificationKind.
const (
	Follow    NotificationKind = "follow"
	Like      NotificationKind = "like"
	OauthLink NotificationKind = "oauth_link"
	Retweet   NotificationKind = "retweet"
)

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Defines values for Provider.
const (
	ProviderGoogle Provider = "google"
	ProviderYandex Provider = "yandex"
)

// Defines values for OauthCallbackParamsProvider.
const (
	OauthCallbackParamsProviderGoogle OauthCallbackParamsProvider = "google"
	OauthCallbackParamsProviderYandex OauthCallbackParamsProvider = "yandex"
)

// Defines values for OauthUnlinkParamsProvider.
const (
	OauthUnlinkParamsProviderGoogle OauthUnlinkParamsProvider = "google"
	OauthUnlinkParamsProviderYandex OauthUnlinkParamsProvider = "yandex"
)

// Defines values for OauthLinkParamsProvider.
const (
	OauthLinkParamsProviderGoogle OauthLinkParamsProvider = "google"
	OauthLinkParamsProviderYandex OauthLinkParamsProvider = "yandex"
)

// Defines values for OauthStartParamsProvider.
const (
	Google OauthStartParamsProvider = "google"
	Yandex OauthStartParamsProvider = "yandex"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Tokens TokenPair   `json:"tokens"`
	User   PrivateUser `json:"user"`
}

// CreateMediaRequest defines model for CreateMediaRequest.
type CreateMediaRequest struct {
	ContentType CreateMediaRequestContentType `json:"content_type"`
	SizeBytes   int                           `json:"size_bytes"`
}

// CreateMediaRequestContentType defines model for CreateMediaRequest.ContentType.
type CreateMediaRequestContentType string

// CreateTweetRequest defines model for CreateTweetRequest.
type CreateTweetRequest struct {
	// MediaIds Each must be in `ready` state.
	MediaIds *[]Id `json:"media_ids,omitempty"`

	// RetweetOfId Snowflake ID as a decimal string (int64-safe in JSON).
	RetweetOfId *Id `json:"retweet_of_id,omitempty"`

	// Text May be empty only when retweet_of_id is set.
	Text string `json:"text"`
}

// Error defines model for Error.
type Error struct {
	// Error Machine-readable code, e.g. validation_failed.
	Error   string `json:"error"`
	Message string `json:"message"`
}

// Id Snowflake ID as a decimal string (int64-safe in JSON).
type Id = string

// LinkStartResponse defines model for LinkStartResponse.
type LinkStartResponse struct {
	// AuthUrl Provider URL to complete linking in the browser.
	AuthUrl string `json:"auth_url"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Login Username or email.
	Login    string `json:"login"`
	Password string `json:"password"`
}

// MarkReadRequest defines model for MarkReadRequest.
type MarkReadRequest struct {
	// UpToId Snowflake ID as a decimal string (int64-safe in JSON).
	UpToId Id `json:"up_to_id"`
}

// Media defines model for Media.
type Media struct {
	// Id Snowflake ID as a decimal string (int64-safe in JSON).
	Id     Id          `json:"id"`
	Status MediaStatus `json:"status"`

	// Urls Populated when status=ready.
	Urls *struct {
		Feed  *string `json:"feed,omitempty"`
		Orig  *string `json:"orig,omitempty"`
		Thumb *string `json:"thumb,omitempty"`
	} `json:"urls"`
}

// MediaStatus defines model for Media.Status.
type MediaStatus string

// MediaRef defines model for MediaRef.
type MediaRef struct {
	// Id Snowflake ID as a decimal string (int64-safe in JSON).
	Id Id `json:"id"`

	// Urls Fixed scheme https://media.{domain}/{variant}/{media_id}.webp (§2.5).
	Urls struct {
		Feed  string `json:"feed"`
		Orig  string `json:"orig"`
		Thumb string `json:"thumb"`
	} `json:"urls"`
}

// MediaUploadTicket defines model for MediaUploadTicket.
type MediaUploadTicket struct {
	ExpiresAt time.Time `json:"expires_at"`

	// MediaId Snowflake ID as a decimal string (int64-safe in JSON).
	MediaId Id `json:"media_id"`

	// UploadUrl Pre-signed PUT, scoped to exact key + content-length-range, 5-min expiry.
	UploadUrl string `json:"upload_url"`
}

// Notification defines model for Notification.
type Notification struct {
	Actor     UserSummary `json:"actor"`
	CreatedAt time.Time   `json:"created_at"`

	// Id Snowflake ID as a decimal string (int64-safe in JSON).
	Id   Id               `json:"id"`
	Kind NotificationKind `json:"kind"`
	Read bool             `json:"read"`

	// SubjectId Tweet ID for like/retweet; null for follow/oauth_link.
	SubjectId *Id `json:"subject_id"`
}

// NotificationKind defines model for Notification.Kind.
type NotificationKind string

// NotificationPage defines model for NotificationPage.
type NotificationPage struct {
	Items      []Notification `json:"items"`
	NextCursor *string        `json:"next_cursor"`
}

// OAuthProviderInfo defines model for OAuthProviderInfo.
type OAuthProviderInfo struct {
	DisplayName string `json:"display_name"`
	Name        string `json:"name"`
	StartUrl    string `json:"start_url"`
}

// PrivateUser defines model for PrivateUser.
type PrivateUser struct {
	AvatarUrl      *string             `json:"avatar_url"`
	Bio            string              `json:"bio"`
	CreatedAt      time.Time           `json:"created_at"`
	Email          openapi_types.Email `json:"email"`
	FollowersCount int                 `json:"followers_count"`
	FollowingCount int                 `json:"following_count"`

	// HasPassword false for OAuth-only accounts (pass_hash NULL).
	HasPassword bool `json:"has_password"`

	// Id Snowflake ID as a decimal string (int64-safe in JSON).
	Id              Id       `json:"id"`
	LinkedProviders []string `json:"linked_providers"`
	Username        string   `json:"username"`
}

// ProviderList defines model for ProviderList.
type ProviderList struct {
	Providers []OAuthProviderInfo `json:"providers"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Omit when the HttpOnly refresh cookie is present (web).
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Access-token lifetime in seconds (900 = 15 min).
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Returned in the body for non-web clients; web clients get a SameSite=Strict HttpOnly cookie instead.
	RefreshToken *string            `json:"refresh_token,omitempty"`
	TokenType    TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// Tweet defines model for Tweet.
type Tweet struct {
	Author    UserSummary `json:"author"`
	CreatedAt time.Time   `json:"created_at"`

	// Id Snowflake ID as a decimal string (int64-safe in JSON).
	Id Id `json:"id"`

	// LikedByMe Present only on authenticated reads.
	LikedByMe *bool `json:"liked_by_me,omitempty"`

	// LikesCount Eventual (±seconds), from the counter pipeline (§2.7).
	LikesCount int         `json:"likes_count"`
	Media      *[]MediaRef `json:"media,omitempty"`

	// RetweetOf One level deep — retweets of retweets are flattened to the original.
	RetweetOf     *Tweet `json:"retweet_of"`
	RetweetsCount int    `json:"retweets_count"`
	Text          string `json:"text"`
}

// TweetPage defines model for TweetPage.
type TweetPage struct {
	Items []Tweet `json:"items"`

	// NextCursor Absent/null on the last page.
	NextCursor *string `json:"next_cursor"`
}

// UnreadCount defines model for UnreadCount.
type UnreadCount struct {
	Count int `json:"count"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	// AvatarMediaId Snowflake ID as a decimal string (int64-safe in JSON).
	AvatarMediaId *Id     `json:"avatar_media_id,omitempty"`
	Bio           *string `json:"bio,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl      *string   `json:"avatar_url"`
	Bio            string    `json:"bio"`
	CreatedAt      time.Time `json:"created_at"`
	FollowersCount int       `json:"followers_count"`
	FollowingCount int       `json:"following_count"`

	// Id Snowflake ID as a decimal string (int64-safe in JSON).
	Id       Id     `json:"id"`
	Username string `json:"username"`
}

// UserPage defines model for UserPage.
type UserPage struct {
	Items      []UserSummary `json:"items"`
	NextCursor *string       `json:"next_cursor"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {
	AvatarUrl *string `json:"avatar_url"`

	// Id Snowflake ID as a decimal string (int64-safe in JSON).
	Id       Id     `json:"id"`
	Username string `json:"username"`
}

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// MediaId Snowflake ID as a decimal string (int64-safe in JSON).
type MediaId = Id

// Provider defines model for Provider.
type Provider string

// TweetId Snowflake ID as a decimal string (int64-safe in JSON).
type TweetId = Id

// Username defines model for Username.
type Username = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// OauthUnlinkParamsProvider defines parameters for OauthUnlink.
type OauthUnlinkParamsProvider string

// OauthLinkParamsProvider defines parameters for OauthLink.
type OauthLinkParamsProvider string

// OauthStartParams defines parameters for OauthStart.
type OauthStartParams struct {
	// RedirectTo SPA route to return to after callback (validated allowlist).
	RedirectTo *string `form:"redirect_to,omitempty" json:"redirect_to,omitempty"`
}

// OauthStartParamsProvider defines parameters for OauthStart.
type OauthStartParamsProvider string

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateMediaParams defines parameters for CreateMedia.
type CreateMediaParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	// Cursor Opaque cursor from the previous page's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// MarkNotificationsReadParams defines parameters for MarkNotificationsRead.
type MarkNotificationsReadParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetHomeTimelineParams defines parameters for GetHomeTimeline.
type GetHomeTimelineParams struct {
	// Cursor Opaque cursor from the previous page's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTweetParams defines parameters for CreateTweet.
type CreateTweetParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UnlikeTweetParams defines parameters for UnlikeTweet.
type UnlikeTweetParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// LikeTweetParams defines parameters for LikeTweet.
type LikeTweetParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateMeParams defines parameters for UpdateMe.
type UpdateMeParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UnfollowUserParams defines parameters for UnfollowUser.
type UnfollowUserParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// FollowUserParams defines parameters for FollowUser.
type FollowUserParams struct {
	// IdempotencyKey UUID dedupe key; 24h window (ARCHITECTURE.md §7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListFollowersParams defines parameters for ListFollowers.
type ListFollowersParams struct {
	// Cursor Opaque cursor from the previous page's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListFollowingParams defines parameters for ListFollowing.
type ListFollowingParams struct {
	// Cursor Opaque cursor from the previous page's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUserTweetsParams defines parameters for GetUserTweets.
type GetUserTweetsParams struct {
	// Cursor Opaque cursor from the previous page's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateMediaJSONRequestBody defines body for CreateMedia for application/json ContentType.
type CreateMediaJSONRequestBody = CreateMediaRequest

// MarkNotificationsReadJSONRequestBody defines body for MarkNotificationsRead for application/json ContentType.
type MarkNotificationsReadJSONRequestBody = MarkReadRequest

// CreateTweetJSONRequestBody defines body for CreateTweet for application/json ContentType.
type CreateTweetJSONRequestBody = CreateTweetRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in with username/email + password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the current refresh-token family
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Provider callback — exchange code, upsert identity, issue tokens
	// (GET /auth/oauth/{provider}/callback)
	OauthCallback(w http.ResponseWriter, r *http.Request, provider OauthCallbackParamsProvider, params OauthCallbackParams)
	// Unlink a provider
	// (DELETE /auth/oauth/{provider}/link)
	OauthUnlink(w http.ResponseWriter, r *http.Request, provider OauthUnlinkParamsProvider)
	// Start linking a provider to the authenticated account
	// (POST /auth/oauth/{provider}/link)
	OauthLink(w http.ResponseWriter, r *http.Request, provider OauthLinkParamsProvider)
	// Begin the authorization-code + PKCE dance
	// (GET /auth/oauth/{provider}/start)
	OauthStart(w http.ResponseWriter, r *http.Request, provider OauthStartParamsProvider, params OauthStartParams)
	// List enabled OAuth providers (config-driven)
	// (GET /auth/providers)
	ListAuthProviders(w http.ResponseWriter, r *http.Request)
	// Rotate the refresh token, issue a new pair
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Create an account
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request, params RegisterParams)
	// Allocate media ID and pre-signed upload URL (§2.5)
	// (POST /media)
	CreateMedia(w http.ResponseWriter, r *http.Request, params CreateMediaParams)
	// Media processing status
	// (GET /media/{id})
	GetMedia(w http.ResponseWriter, r *http.Request, id MediaId)
	// Confirm upload — verifies object exists, emits MediaUploaded via outbox
	// (POST /media/{id}/complete)
	CompleteMedia(w http.ResponseWriter, r *http.Request, id MediaId)
	// List notifications (eventual, <30s)
	// (GET /notifications)
	ListNotifications(w http.ResponseWriter, r *http.Request, params ListNotificationsParams)
	// Mark all notifications up to an ID as read
	// (POST /notifications/read)
	MarkNotificationsRead(w http.ResponseWriter, r *http.Request, params MarkNotificationsReadParams)
	// Unread badge counter
	// (GET /notifications/unread_count)
	GetUnreadCount(w http.ResponseWriter, r *http.Request)
	// Home timeline (hybrid fan-out merge, §2.1; eventual <5s)
	// (GET /timeline)
	GetHomeTimeline(w http.ResponseWriter, r *http.Request, params GetHomeTimelineParams)
	// Create a tweet or retweet (retweet_of_id set)
	// (POST /tweets)
	CreateTweet(w http.ResponseWriter, r *http.Request, params CreateTweetParams)
	// Delete own tweet
	// (DELETE /tweets/{id})
	DeleteTweet(w http.ResponseWriter, r *http.Request, id TweetId)
	// Fetch one tweet
	// (GET /tweets/{id})
	GetTweet(w http.ResponseWriter, r *http.Request, id TweetId)
	// Unlike (idempotent)
	// (DELETE /tweets/{id}/like)
	UnlikeTweet(w http.ResponseWriter, r *http.Request, id TweetId, params UnlikeTweetParams)
	// Like (idempotent — PK ON CONFLICT DO NOTHING)
	// (POST /tweets/{id}/like)
	LikeTweet(w http.ResponseWriter, r *http.Request, id TweetId, params LikeTweetParams)
	// Current user's profile (read-your-writes)
	// (GET /users/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Update profile
	// (PATCH /users/me)
	UpdateMe(w http.ResponseWriter, r *http.Request, params UpdateMeParams)
	// Public profile
	// (GET /users/{username})
	GetUser(w http.ResponseWriter, r *http.Request, username Username)
	// Unfollow a user (idempotent)
	// (DELETE /users/{username}/follow)
	UnfollowUser(w http.ResponseWriter, r *http.Request, username Username, params UnfollowUserParams)
	// Follow a user (idempotent; writes both edge tables + event in one tx)
	// (POST /users/{username}/follow)
	FollowUser(w http.ResponseWriter, r *http.Request, username Username, params FollowUserParams)
	// Who follows this user
	// (GET /users/{username}/followers)
	ListFollowers(w http.ResponseWriter, r *http.Request, username Username, params ListFollowersParams)
	// Who this user follows
	// (GET /users/{username}/following)
	ListFollowing(w http.ResponseWriter, r *http.Request, username Username, params ListFollowingParams)
	// Profile timeline
	// (GET /users/{username}/tweets)
	GetUserTweets(w http.ResponseWriter, r *http.Request, username Username, params GetUserTweetsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OauthCallback operation middleware
func (siw *ServerInterfaceWrapper) OauthCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider OauthCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OauthCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OauthCallback(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OauthUnlink operation middleware
func (siw *ServerInterfaceWrapper) OauthUnlink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider OauthUnlinkParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OauthUnlink(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OauthLink operation middleware
func (siw *ServerInterfaceWrapper) OauthLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider OauthLinkParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OauthLink(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OauthStart operation middleware
func (siw *ServerInterfaceWrapper) OauthStart(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider OauthStartParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params OauthStartParams

	// ------------- Optional query parameter "redirect_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect_to", r.URL.Query(), &params.RedirectTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OauthStart(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuthProviders operation middleware
func (siw *ServerInterfaceWrapper) ListAuthProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuthProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMedia operation middleware
func (siw *ServerInterfaceWrapper) CreateMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateMediaParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMedia(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMedia operation middleware
func (siw *ServerInterfaceWrapper) GetMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MediaId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMedia(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteMedia operation middleware
func (siw *ServerInterfaceWrapper) CompleteMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id MediaId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteMedia(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotifications operation middleware
func (siw *ServerInterfaceWrapper) ListNotifications(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotificationsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotifications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkNotificationsRead operation middleware
func (siw *ServerInterfaceWrapper) MarkNotificationsRead(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params MarkNotificationsReadParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkNotificationsRead(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUnreadCount operation middleware
func (siw *ServerInterfaceWrapper) GetUnreadCount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUnreadCount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHomeTimeline operation middleware
func (siw *ServerInterfaceWrapper) GetHomeTimeline(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHomeTimelineParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHomeTimeline(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTweet operation middleware
func (siw *ServerInterfaceWrapper) CreateTweet(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTweetParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTweet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTweet operation middleware
func (siw *ServerInterfaceWrapper) DeleteTweet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TweetId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTweet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTweet operation middleware
func (siw *ServerInterfaceWrapper) GetTweet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TweetId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTweet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnlikeTweet operation middleware
func (siw *ServerInterfaceWrapper) UnlikeTweet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TweetId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UnlikeTweetParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnlikeTweet(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LikeTweet operation middleware
func (siw *ServerInterfaceWrapper) LikeTweet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TweetId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params LikeTweetParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LikeTweet(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateMeParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnfollowUser operation middleware
func (siw *ServerInterfaceWrapper) UnfollowUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UnfollowUserParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnfollowUser(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FollowUser operation middleware
func (siw *ServerInterfaceWrapper) FollowUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params FollowUserParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FollowUser(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFollowers operation middleware
func (siw *ServerInterfaceWrapper) ListFollowers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFollowersParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFollowers(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFollowing operation middleware
func (siw *ServerInterfaceWrapper) ListFollowing(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFollowingParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFollowing(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserTweets operation middleware
func (siw *ServerInterfaceWrapper) GetUserTweets(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserTweetsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserTweets(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc("POST "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc("GET "+options.BaseURL+"/auth/oauth/{provider}/callback", wrapper.OauthCallback)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/oauth/{provider}/link", wrapper.OauthUnlink)
	m.HandleFunc("POST "+options.BaseURL+"/auth/oauth/{provider}/link", wrapper.OauthLink)
	m.HandleFunc("GET "+options.BaseURL+"/auth/oauth/{provider}/start", wrapper.OauthStart)
	m.HandleFunc("GET "+options.BaseURL+"/auth/providers", wrapper.ListAuthProviders)
	m.HandleFunc("POST "+options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	m.HandleFunc("POST "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc("POST "+options.BaseURL+"/media", wrapper.CreateMedia)
	m.HandleFunc("GET "+options.BaseURL+"/media/{id}", wrapper.GetMedia)
	m.HandleFunc("POST "+options.BaseURL+"/media/{id}/complete", wrapper.CompleteMedia)
	m.HandleFunc("GET "+options.BaseURL+"/notifications", wrapper.ListNotifications)
	m.HandleFunc("POST "+options.BaseURL+"/notifications/read", wrapper.MarkNotificationsRead)
	m.HandleFunc("GET "+options.BaseURL+"/notifications/unread_count", wrapper.GetUnreadCount)
	m.HandleFunc("GET "+options.BaseURL+"/timeline", wrapper.GetHomeTimeline)
	m.HandleFunc("POST "+options.BaseURL+"/tweets", wrapper.CreateTweet)
	m.HandleFunc("DELETE "+options.BaseURL+"/tweets/{id}", wrapper.DeleteTweet)
	m.HandleFunc("GET "+options.BaseURL+"/tweets/{id}", wrapper.GetTweet)
	m.HandleFunc("DELETE "+options.BaseURL+"/tweets/{id}/like", wrapper.UnlikeTweet)
	m.HandleFunc("POST "+options.BaseURL+"/tweets/{id}/like", wrapper.LikeTweet)
	m.HandleFunc("GET "+options.BaseURL+"/users/me", wrapper.GetMe)
	m.HandleFunc("PATCH "+options.BaseURL+"/users/me", wrapper.UpdateMe)
	m.HandleFunc("GET "+options.BaseURL+"/users/{username}", wrapper.GetUser)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/{username}/follow", wrapper.UnfollowUser)
	m.HandleFunc("POST "+options.BaseURL+"/users/{username}/follow", wrapper.FollowUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{username}/followers", wrapper.ListFollowers)
	m.HandleFunc("GET "+options.BaseURL+"/users/{username}/following", wrapper.ListFollowing)
	m.HandleFunc("GET "+options.BaseURL+"/users/{username}/tweets", wrapper.GetUserTweets)

	return m
}
